# Generated by Django 3.1.6 on 2021-05-21 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.BooleanField(default=False),
        ),
    ]
