# Generated by Django 3.1.6 on 2021-06-16 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating_app', '0006_auto_20210521_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(null=True, upload_to='user_profile_photos'),
        ),
    ]
