# Generated by Django 3.2.4 on 2021-06-17 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating_app', '0008_auto_20210616_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='interest',
            field=models.CharField(blank=True, help_text='Eg. swimming reading travelling singing jogging', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('', '- - -')], default='', max_length=1),
        ),
    ]
