# Generated by Django 3.2.4 on 2021-06-17 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dating_app', '0009_auto_20210617_1116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='interest',
            new_name='interests',
        ),
    ]
